name: serviapp
description: "A new Flutter project."
publish_to: 'none' # No se publicará en pub.dev
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0 # 👈 Dependencia WebSocket

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/perfil.png